// packages/react/src/MatchyTableBootstrap.tsx
import React from 'react';

export interface MatchyTableBootstrapProps {
  data: Record<string, string>[];
  headers: string[];
  invalidCells?: Array<{ row: number; col: number; field: string; errors: Array<{ field: string; message: string }> }>;
  className?: string;
  striped?: boolean;
  hover?: boolean;
  bordered?: boolean;
  condensed?: boolean;
}

export function MatchyTableBootstrap({
  data,
  headers,
  invalidCells = [],
  className = '',
  striped = true,
  hover = true,
  bordered = false,
  condensed = false,
}: MatchyTableBootstrapProps) {
  const isInvalid = (rowIndex: number, colIndex: number) =>
    invalidCells.some(cell => cell.row === rowIndex && cell.col === colIndex);

  const getErrors = (rowIndex: number, colIndex: number): string[] => {
    const cell = invalidCells.find(cell => cell.row === rowIndex && cell.col === colIndex);
    return cell?.errors.map(e => e.message) || [];
  };

  const tableClasses = [
    'table',
    striped && 'table-striped',
    hover && 'table-hover',
    bordered && 'table-bordered',
    condensed && 'table-condensed',
  ].filter(Boolean).join(' ');

  return (
    <div className="table-responsive">
      <table className={`${tableClasses} ${className}`}>
        <thead className="table-dark">
          <tr>
            {headers.map((h, i) => (
              <th key={i} scope="col">{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {data.map((row, rowIdx) => (
            <tr key={rowIdx}>
              {headers.map((h, colIdx) => {
                const errors = getErrors(rowIdx, colIdx);
                const hasError = isInvalid(rowIdx, colIdx);
                return (
                  <td
                    key={colIdx}
                    className={hasError ? 'table-danger' : ''}
                    title={errors.join('\n')}
                  >
                    {row[h]}
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// packages/angular/src/matchy-table-bootstrap.component.ts
import { Component, Input } from '@angular/core';

export interface InvalidCell {
  row: number;
  col: number;
  field: string;
  errors: Array<{ field: string; message: string }>;
}

@Component({
  selector: 'csv-matchy-table-bootstrap',
  template: `
    <div class="table-responsive">
      <table [class]="tableClass">
        <thead class="table-dark">
          <tr>
            <th *ngFor="let header of headers">{{ header }}</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let row of data; let i = index">
            <td
              *ngFor="let header of headers; let j = index"
              [class.table-danger]="isInvalid(i, j)"
              [title]="getErrors(i, j)"
            >
              {{ row[header] }}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  `,
})
export class MatchyTableBootstrapComponent {
  @Input() data: Record<string, string>[] = [];
  @Input() headers: string[] = [];
  @Input() invalidCells: InvalidCell[] = [];
  @Input() tableClass = 'table table-striped table-hover';

  isInvalid(row: number, col: number): boolean {
    return this.invalidCells.some(cell => cell.row === row && cell.col === col);
  }

  getErrors(row: number, col: number): string {
    const cell = this.invalidCells.find(c => c.row === row && c.col === col);
    return cell?.errors.map(e => e.message).join('\n') || '';
  }
}
